const industries = [
    "Accounting - 會計界",
    "Advertising & Marketing & Marketing Research - 廣告 & 市場 & 市場研究",
    "Agriculture, Forestry & Fishing - 農林漁業",
    "Architecture - 建築",
    "Automobile - 汽車工業",
    "Aviation - 航空業",
    "Bakery - 烘焙",
    "Banking & Finance - 金融銀行界",
    "Beauty - 美容",
    "Biotechnology - 生物科技",
    "Building & Construction - 建築業",
    "Civil Engineering - 土木工程",
    "Company Secretary - 公司秘書",
    "Conglomerate - 企業集團",
    "Consulting Firms - 諮詢",
    "Cultural  - 文化界",
    "Dentistry  - 牙醫",
    "Design & Creative Media & Art - 設計 & 創意媒體 & 藝術",
    "Disciplined Services - 紀律部隊",
    "Early Child Education - 幼兒教育",
    "Ecommerce - 電子商務",
    "Education - 教育界",
    "Electrical & Mechanical Engineering  - 機電與機械工程",
    "Electrical Engineering - 電機工程",
    "Electronic Engineering - 電子工程",
    "Elevator Industry - 電梯業",
    "Entertainment - 娛樂",
    "Environmental - 環境",
    "Exhibition and Promotion - 展覽及推廣",
    "Fire Engineering - 消防工程",
    "Fitness - 健身",
    "Food & Beverage - 餐飲業",
    "Freight forwarding - 物流業",
    "Government - 政府",
    "Hair Stylist - 髮型界",
    "Hospitality - 酒店旅遊業",
    "Human Resources - 人力資源界",
    "Information Technology - 資訊科技",
    "Insurance - 保險界",
    "Interior design  - 室內設計",
    "Investment Bank - 投資銀行",
    "Jewelry - 珠寶",
    "Landscape Design  - 園藝設計",
    "Law - 法律界",
    "Manufacturing & Garment & Textile - 製造業",
    "Mathconcept - 數學思維",
    "Media - 新聞傳播界",
    "Medical Beauty - 醫學美容",
    "Medicine & Pharmaceutical - 醫藥",
    "Merchandise Trading - 商品貿易",
    "Merchandising - 採購界",
    "Music - 音樂介別",
    "Pawnbroking -  典當業",
    "Printing - 印刷",
    "Property & Property Management - 地產 & 物業管理",
    "Public Health & Hospital Authority -  公共衛生 & 醫院管理局",
    "Research & Laboratory - 科研學術界",
    "Retail/Fast-Moving Consumer Goods - 零售業",
    "Shipping - 航運",
    "Social Services - 社福界",
    "Telecommunication - 電訊業",
    "Testing and Certification - 檢測及認證業",
    "Textile - 紡織業",
    "Translation  - 翻譯",
    "Transportation & Logistics - 運輸與物流",
    "Utility - 公用事業",
    "Veterinary - 獸醫"
];
const companies = [
    "AsiaPac Net Media Limited - 亞太網絡資訊有限公司",
    "Cargo Services Far East - 嘉宏航運有限公司",
    "CMA CGM (Hong Kong) Limited - 達飛海運",
    "DDB Group Hong Kong - 恆美廣告公司",
    "Francfranc Hong Kong -  Francfranc Hong Kong",
    "FSE Engineering Group Limited - 豐盛機電工程集團有限公司",
    "IT-ec (HK) Limited -  IT-ec (HK) Limited",
    "Media-Go Engineering Ltd. -  Media-Go Engineering Ltd.",
    "Ping An OneConnect Bank (Hong Kong) Limited -  平安壹賬通銀行",
    "Swire Coca-Cola - 太古可樂",
    "The Hong Kong University of Science and Technology (HKUST) - 香港科技大學",
    "3HK - 3香港",
    "A&B - A&B",
    "AASSA - AASSA",
    "Able Engineering - Able Engineering",
    "Accenture - 埃森哲",
    "ACME metal - 益美",
    "ACW Distribution (HK) Ltd - ACW Distribution (HK) Ltd",
    "Adidas Hong Kong - Adidas Hong Kong",
    "Advanced Electronic Technology - Advanced Electronic Technology",
    "AECOM - 艾奕康",
    "AEON Stores (Hong Kong) Co., Limited - 永旺(香港)百貨有限公司",
    "Aggressive Construction Company Ltd. - 精進建築有限公司",
    "AIA - 友邦保險香港",
    "Airport Authority - 機場管理局",
    "AKAR SKIN LIMITED - AKAR SKIN LIMITED",
    "ALE & Co. - ALE & Co.",
    "AlikeAudience - AlikeAudience",
    "Allegis  - Allegis",
    "Allied Environmental Consultants Limited - 沛然環境評估工程顧問有限公司",
    "Allied Success - Allied Success",
    "Alvarez & Marsal Asia Limited - Alvarez & Marsal Asia Limited",
    "American Express - 美國運通",
    "Amore Pacific - Amore Pacific",
    "Ample Capital Limited - 豐盛融資有限公司",
    "AMTD Financial Planning Limited - AMTD Financial Planning Limited",
    "Analytic Partners - Analytic Partners",
    "Anglo-Eastern Ship Management Ltd. - Anglo-Eastern Ship Management Ltd.",
    "AnyPet clinic - AnyPet clinic",
    "API Lab Testing Limited - 法亞太產品測試有限公司",
    "Apple Inc. - 蘋果",
    "Appledaily - 蘋果日報",
    "Arcadis - Arcadis",
    "Arjo Systems Limited - Arjo Systems Limited",
    "Artesyn Embedded Technologies - Artesyn Embedded Technologies",
    "Arthur Yung and Associates Limited - 容亨達工程師事務所",
    "Arup - Arup",
    "ASM Pacific Technology -  ASM Pacific Technology",
    "ASM Pacific Technology - ASM Pacific Technology",
    "ASSOCIATION OF BAPTISTS FOR WORLD EVANGELISM (HK) LIMITED - ASSOCIATION OF BAPTISTS FOR WORLD EVANGELISM (HK) LIMITED",
    "ASTRI - 應科院",
    "ATAL - ATAL",
    "Atkins China Ltd - Atkins China Ltd",
    "Atl - 安樂",
    "Automated Systems (HK) Limited (ASL) - Automated Systems (HK) Limited (ASL)",
    "Avaya Hong Kong Company Limited - Avaya Hong Kong Company Limited",
    "Avnet Technology Hong Kong Ltd. - Avnet Technology Hong Kong Ltd.",
    "AWIN PRODUCTION AND MANAGEMENT - AWIN PRODUCTION AND MANAGEMENT",
    "AXA - 安盛",
    "B P International - B P International",
    "BAI COMMUNICATIONS HONG KONG - BAI COMMUNICATIONS HONG KONG",
    "Bain & Company - Bain & Company",
    "Baker McKenzie - Baker McKenzie",
    "Baker Tilly Hong Kong Limited - 天職香港",
    "Bank of America Merrill Lynch - 美銀美林集團",
    "Bank of China (HK) (BOC) - 中銀香港",
    "Bank of China (HK) (International) (BOCI) - 中銀國際",
    "Bank of Communications - Bank of Communications",
    "Bank of East Asia, Limited - 東亞銀行",
    "Barclays - 巴克萊銀行",
    "BCR - BCR",
    "BDO Limited - 香港立信德豪會計師事務所",
    "Be With You Programme Education Organization - Be With You Programme Education Organization",
    "Beacon College Ltd - 遵理學校有限公司",
    "BGI  - 華大基因",
    "Bloomberg - 彭博",
    "Blue Insurance Limited - 微藍保險有限公司",
    "Blue Umbrella - Blue Umbrella",
    "BNP Paribas - 法國巴黎銀行",
    "BOC GROUP LIFE ASSURANCE COMPANY LIMITED - 中銀人壽",
    "Boston Consulting Group (BCG) - Boston Consulting Group (BCG)",
    "Bright Future Pharmaceutical Laboratories Ltd - Bright Future Pharmaceutical Laboratories Ltd",
    "Bright Future Pharmaceutical Laboratories Ltd - 澳美製藥廠",
    "Brilliant Building Materials Ltd - Brilliant Building Materials Ltd",
    "Brink's Japan Limited - Brink's Japan Limited",
    "BT International - BT International",
    "Budd Technology Limited (GoBuddy) - Budd Technology Limited (GoBuddy)",
    "Buildings Department - 屋宇署",
    "BuildKing Construction Limited - 利基控股有限公司",
    "Bupa (Asia) Limited - 保柏(亞洲)有限公司",
    "Burberry - Burberry",
    "Bureau Veritas - Bureau Veritas",
    "Cafe de carol - 大家樂",
    "Cainiao Smart Network (Alibaba Group) - 菜鳥",
    "California Insurance - California Insurance",
    "Camex Jewellery Limited - Camex Jewellery Limited",
    "Canon Electronics Business Machines - 佳能電產",
    "Capco - Capco",
    "Cardinalasia Consulting Limited - Cardinalasia Consulting Limited",
    "Caritas Hong Kong - Caritas Hong Kong",
    "Carrier Hong Kong limited  - 開利（香港）有限公司",
    "Cathay Pacific - 國泰航空",
    "Cathay Pacific Catering - 國泰航空飲食服務(香港)",
    "Cathy Chung Academy Limited - Cathy Chung Academy Limited",
    "CBRE - CBRE",
    "CEB - CEB",
    "Central Business Information Limited - 滙華商業資訊有限公司",
    "Chamc - Chamc",
    "Chan Sui Ki (La Salle) Primary School - 陳瑞祺（喇沙）小學",
    "Chateau Zoobeetle Limited - Chateau Zoobeetle Limited",
    "Cherrypicks - 創奇思",
    "Cheung Kong Property Holdings Limited - Cheung Kong Property Holdings Limited",
    "Chevalier - Chevalier",
    "Chief Securities Limited - 致富證券有限公司",
    "China Construction Bank (Asia) (CCB) - 中國建設銀行(亞洲)",
    "China Mobile Hong Kong - 中國移動香港",
    "China Mobile International - 中國移動國際",
    "China Patent Agent (H.K.) Ltd. - China Patent Agent (H.K.) Ltd.",
    "China Road and Bridge Corporation - 中國路橋工程有限責任公司",
    "China State Construction Engineering (Hong Kong) Limited - 中國建築國際集團有限公司",
    "China Telecom Global - 中國電信",
    "Chinachem group - 華懋",
    "Chinese Bible International Limited - 漢語聖經協會",
    "Chinese Estates Holdings Limited - 華人置業集團",
    "Chiyu Bank - 集友銀行",
    "Chocolate Asset Management - 巧力資產管理",
    "Christie's Auction House - Christie's Auction House",
    "Chubb - 安達",
    "Chun Wo Building Construction Limited - 俊和建築有限公司",
    "CIAO International Limited  - 優品360",
    "CIMB - CIMB",
    "Citadel (Hong Kong) Limited - Citadel (Hong Kong) Limited",
    "Citibank - 花旗銀行",
    "Citibank (Hong Kong) - 花旗銀行(香港)",
    "Citic Bank - 中信銀行",
    "Citic Telecom International CPC limited - 中信國際電訊",
    "City Super Limited - City Super Limited",
    "City University of Hong Kong - 香港城市大學",
    "CityBase - 港基",
    "Cityray Technology - 施特偉",
    "Civil Engineering and Development Department (CEDD) - 土木工程拓展署",
    "Classroom334 Limited - Classroom334 Limited",
    "Cloud Commerce Systems Limited - Cloud Commerce Systems Limited",
    "CLP Engineering Limited - 中電工程有限公司",
    "CLP Power Hong Kong Limited - 中電",
    "CM Wong & Associates - CM Wong & Associates",
    "CMA Secondary School - CMA Secondary School",
    "CMB International - CMB International",
    "CMB Wing Lung Bank  - 招商永隆銀行",
    "Cnt - Cnt",
    "Coface - Coface",
    "Coface Trade Credit Insurance - 科法斯集團",
    "Cognizant - 高知特",
    "Coleman Research Hong Kong Limited - Coleman Research Hong Kong Limited",
    "Colgate-Palmolive - 高露潔",
    "Colliers - Colliers",
    "Commercial Radio - 商業電台",
    "Commercial Real Estate Services (CBRE) - Commercial Real Estate Services (CBRE)",
    "COMPTIFY ANALYTICS LIMITED - COMPTIFY ANALYTICS LIMITED",
    "Computer And Technologies Holdings Limited - Computer And Technologies",
    "Conrad Hong Kong - 港麗酒店",
    "CORIGINE (HONG KONG) LIMITED - CORIGINE (HONG KONG) LIMITED",
    "Cosmo Physiotherapy Centre - Cosmo Physiotherapy Centre",
    "CR Construction - 華營建築有限公司",
    "Credit Agricole - Credit Agricole",
    "Credit Suisse - 瑞信",
    "Credit Suisse Group AG - 瑞士信貸集團股份有限公司",
    "Crystal Group - Crystal Group",
    "CTBC - 中國信託",
    "Cundall - Cundall",
    "Cyel - Cyel",
    "Dah Chong Hong - 大昌行集團有限公司",
    "Dah Sing Banking Group Limited - 大新銀行有限公司",
    "Dairy Farm Group - 牛奶公司集團",
    "David Zwirner - David Zwirner",
    "DBS Bank (Hong Kong) Limited - 星展銀行",
    "Deacons - Deacons",
    "Debevoise & Plimpton - 德普律師事務所",
    "Deloitte Touche Tohmatsu Limited - 德勤",
    "Department of Justice - 律政司",
    "Deutsche Bank - 德意志銀行",
    "DFO  - DFO",
    "DFS Group - DFS Group",
    "DHL - DHL",
    "Dicky Suen & Company - Dicky Suen & Company",
    "DigitasLbi Razorfish - DigitasLbi Razorfish",
    "Discovery Technologies Limited - Discovery Technologies Limited",
    "DJI - 大疆",
    "Dorsett Hospitality International -  帝盛酒店集團",
    "Dow Jones Publishing Co (Asia) Inc - Dow Jones Publishing Co (Asia) Inc",
    "Dragages - Dragages",
    "Dyxnet group - 第一線集團",
    "E-print - E-print",
    "EBCD - EBCD",
    "Edelman - Edelman",
    "Edlab Limited - 匯文教室有限公司",
    "Edvance Technology (Hong Kong) Limited - 安領科技（香港）有限公司",
    "EGUSI - EGUSI",
    "Electrical and Mechanical Services Department (EMSD) - 機電工程署",
    "Elegance Finance Printing Services Ltd. - Elegance Finance Printing Services Ltd.",
    "ELEVATE Global - 達岸諮詢有限公司",
    "Eli Lilly - Eli Lilly",
    "Emperor Group - 英皇集團",
    "Empire Hotels - 港島皇悅酒店",
    "Environmental Protection Department  - 環保署",
    "Ernst & Young Global Limited (EY) - 安永會計師事務所",
    "Esquel Group - Esquel Group",
    "Estee Lauder Companies  - Estee Lauder Companies",
    "EternityX - EternityX",
    "Everbest Insurance and Financial Services Limited - Everbest Insurance and Financial Services Limited",
    "Everbest Technology Limited - 永佳科技電子有限公司",
    "Everbright Sun Hung Kai Company Limited - 光大新鴻基有限公司",
    "Everlight engineer company ltd - 恆安",
    "Eversheds Sutherland - 安睿順徳倫律師事務所",
    "FDM Group - FDM Group",
    "Finsbury - 富思博睿",
    "First Technology - 株式会社ファーストテクノロジー",
    "Flexport - Flexport",
    "Four Seasons Hotels Limited - 四季酒店集團",
    "Freshfields Bruckhaus Deringer LLP - Freshfields Bruckhaus Deringer LLP",
    "FRONTIER RESEARCH AND TECHNOLOGY LIMITED - FRONTIER RESEARCH AND TECHNOLOGY LIMITED",
    "FS - FS",
    "Fubon Bank Hong Kong - 富邦銀行香港",
    "Fugro - 輝固",
    "Fuji Xerox - 富士施樂",
    "Fujitec - 富士達",
    "Fulbright Financial Group -  富昌金融集團",
    "Funful Group of Schools - 方方樂趣教育機構",
    "Fung Cheung Kee Group - 馮祥記集團",
    "G4S - G4S",
    "G2000 Group - G2000 集團",
    "Gagosian - 高古斯",
    "Gammon Construction Limited - 金門建築有限公司",
    "GE Medical Systems Hong Kong Ltd - GE Medical Systems Hong Kong Ltd",
    "Gelec - Gelec",
    "Geodis - Geodis",
    "Giraffe Capital Limited - 智富融資有限公司",
    "GlaxoSmithKline Limited - GlaxoSmithKline Limited",
    "Global Fine Foods Limited - Global Fine Foods Limited",
    "GoGoVan - GoGoVan",
    "Goldman Sachs - 高盛",
    "Google - Google",
    "GP Battery Marketing (HK) Ltd - GP Battery Marketing (HK) Ltd",
    "Grand Finance Group Company Limited - Grand Finance Group Company Limited",
    "Grant Thornton - Grant Thornton",
    "Greater China Wealth & Risk Management Limited - Greater China Wealth & Risk Management Limited",
    "Green Tomato Ltd. - Green Tomato Ltd.",
    "GSK - GSK",
    "GU Hong Kong Apparel Limited - GU Hong Kong Apparel Limited",
    "Haitong International Securities Group Limited - 海通國際證券集團有限公司",
    "Handlebook Education Solutions Limited - Handlebook Education Solutions Limited",
    "Hang Lung Group - 恒隆集團",
    "Hang Seng Bank Limited - 恒生銀行",
    "Hanison - Hanison",
    "Harbour Plastic Molding Company Limited - Harbour Plastic Molding Company Limited",
    "Harmay Co., Limited - 話梅(香港)有限公司",
    "Harriman Property Management Limited - 夏利文物業管理有限公司",
    "Havi - 夏暉",
    "Henderson Land Development Co. Ltd. - 恆基兆業地產有限公司",
    "Herbert Smith Freehills - Herbert Smith Freehills",
    "HGC Global Communications Limited - 環球全域電訊有限公司",
    "Hi Chau construction co Ltd - 浩洲建築有限公司",
    "Hilti - Hilti",
    "Hip Hing Construction Co., Ltd - 協興建築有限公司",
    "HK01 - 香港01",
    "HKCS - 香港基督教服務處",
    "HKEX - 港交所",
    "HKSAR Government - 香港政府",
    "HKSAR Government (Correctional Services Department) - 香港懲教署",
    "HKSAR Government (Immigration Department) - 入境事務處",
    "HKSAR Government (Information Services Department) - 政府新聞處",
    "HKT Limited -  香港電訊",
    "HKTVmall -  香港電視",
    "HKU Clinical Trial Centre - 香港大學臨床研究中心",
    "HLB Hodgson Impey Cheng Limited - HLB Hodgson Impey Cheng Limited",
    "HNA - 海航集團",
    "HNA Group (International) CO.,LTD - 海航國際",
    "Hogan Lovells - Hogan Lovells",
    "Home Affairs Department - 民政事務總署",
    "Hong Kong Aero Engine Services Limited (HAESL) - 香港航空發動機維修服務有限公司",
    "Hong Kong Air Cargo Terminals Limited (Hactl) - 香港空運貨站",
    "Hong Kong Aircraft Engineering Company Limited (HAECO) - 香港飛機工程有限公司",
    "Hong Kong Airline - 香港航空",
    "Hong Kong Baptist University - 香港浸會大學",
    "Hong Kong Broadband Network Limited - 香港寬頻網絡有限公司",
    "Hong Kong Chan Lo Yi Medicine Co Ltd - 香港陳老二藥廠有限公司",
    "Hong Kong Council of Social Services - 香港社會服務聯會",
    "Hong Kong Disneyland - 香港迪士尼樂園",
    "Hong Kong District Cooling - 香港區域供冷",
    "Hong Kong Economies Times Limited - 經濟日報",
    "Hong Kong Education Services Center - Hong Kong Education Services Center",
    "Hong Kong Electric - 港燈",
    "Hong Kong Fire Services Department - 消防處",
    "Hong Kong Housing Authority and Housing Department - 香港房屋委員會",
    "Hong Kong Housing Society - 香港房屋協會",
    "Hong Kong Interbank Clearing Limited - 香港銀行同業結算有限公司",
    "Hong Kong International Airport - 香港國際機場",
    "Hong Kong Jockey Club - 香港賽馬會",
    "Hong Kong Monetary Authority (HKMA) - 香港金融管理局",
    "Hong Kong Police Force - 香港警務處",
    "Hong Kong Productivity Council - 生產力局",
    "Hong Kong Quality Assurance Agency - 香港品質保證局",
    "Hong Kong Sanatorium & Hospital Limited - 養和醫院",
    "Hong Kong Telecommunication (HKT) Services Limited - 香港電訊",
    "Hong Kong Trade Development Council (HKTDC) - 香港貿發局",
    "Hong Yip Service Co. Ltd. - 康業服務有限公司",
    "Hop Lun (H.K.) Ltd - 合隆香港有限公司",
    "Hopewell Holdings Ltd - 合和控股有限公司",
    "Hospital Authority - 醫院管理局",
    "Housing Authority - 香港房屋委員會及房屋署",
    "Hsin Chong Group Holdings Limited - 新昌集團控股有限公司",
    "Huawei Technologies Co., Ltd. - 華為技術有限公司",
    "HUMAN ASSET DEVELOPMENT COMPANY - HUMAN ASSET DEVELOPMENT COMPANY",
    "Hutchgo.com - Hutchgo.com",
    "Hutchison Ports - 和記港口",
    "Hutchison Telecom - 和記電訊",
    "i-Cable News Limited - 有線新聞",
    "I.T. - I.T.",
    "iAdvantage Limited - 互聯優勢有限公司",
    "IBM - IBM",
    "ICAC - 廉政公署",
    "iCreate - iCreate",
    "IKEA Hong Kong - 宜家家居",
    "Image Optical  - 潮流天地",
    "Imagine Software - Imagine Software",
    "Imsight Medical Technology Company Limited - Imsight Medical Technology Company Limited",
    "Industrial and Commercial Bank of China, Dubai (DIFC) Branch - 中國工商銀行",
    "Infinite Financial Solutions Limited - Infinite Financial Solutions Limited",
    "Innotek electronic ltd.  - Innotek electronic ltd.",
    "International Scholars Tuition School (Hong Kong) - International Scholars Tuition School (Hong Kong)",
    "Intertek Testing Services Hong Kong Ltd. - 天祥公證行有限公司",
    "iOne - iOne",
    "IPSOS Limited - IPSOS Limited",
    "ISS Facility Ltd - ISS Facility Ltd",
    "ITOCHU Hong Kong Ltd. - 伊藤忠商事（香港）有限公司",
    "Jacobson Pharma Group - Jacobson Pharma Group",
    "Jardine - 怡和集團",
    "Jardine Aviation Services - 怡中航空服務",
    "Jardine Engineering Corporation - 怡和工程公司",
    "Jardine One Solution - 怡和科技",
    "JDEA Company - JDEA Company",
    "Jobs DB Hong Kong Limited - Jobs DB Hong Kong Limited",
    "Johnson Control - 江深自控",
    "Jones Lang LaSalle Ltd - Jones Lang LaSalle Ltd",
    "Jones Lang LaSalle Management Services Limited - 仲量聯行物業管理有限公司",
    "JP Morgan - 摩根大通",
    "Jusco - 吉之島",
    "Kai shing - 啟勝",
    "Kai Shing Management Services Limited - 啟勝管理服務有限公司",
    "KC & Partners CPA Limited - KC & Partners CPA Limited",
    "Keio engineering  - Keio engineering",
    "KEN CHAN & CO., CERTIFIED PUBLIC ACCOUNTANTS - KEN CHAN & CO., CERTIFIED PUBLIC ACCOUNTANTS",
    "Kerry Logistics (Hong Kong) Limited - 嘉里物流",
    "Kin Wing Engineering Co. Ltd - 建榮地基有限公司",
    "King & Wood Mallesons - King & Wood Mallesons",
    "Klook Travel Technology Limited - Klook Travel Technology Limited",
    "KMB - 九巴",
    "KPMG - 畢馬威",
    "KPMG International Limited - KPMG International Limited",
    "Kuehne & Nagel Limited - 德迅",
    "Kum Shing Group - 金城營造集團",
    "Kumon Tai Po Education Centre - Kumon Tai Po Education Centre",
    "L'hotel - L'hotel",
    "L'Oréal Hong Kong Limited - L'Oréal Hong Kong Limited",
    "Labour Department - 勞工處",
    "Langdon and Seah - Langdon and Seah",
    "Lee Kum Kee - 李錦記",
    "Leica Geosystems HK - 徠卡測量系統有限公司(香港)",
    "Leisure and Cultural Services Department - 康樂及文化事務署",
    "Lenovo Group Limited - Lenovo Group Limited",
    "LF ASIA - 利豐亞洲(香港)",
    "LF Logistics - 利豐物流",
    "LGT Bank - LGT Bank",
    "Link REIT - 領展",
    "Linklaters - Linklaters",
    "LK INTERNATIONAL (H.K) LIMITED - LK INTERNATIONAL (H.K) LIMITED",
    "Lloyd's Register - Lloyd's Register",
    "Local Psychiatric Hospital - Local Psychiatric Hospital",
    "Lockton Companies (Hong Kong) Ltd - Lockton Companies (Hong Kong) Ltd",
    "Lofty Aspirations Consultants Ltd. - Lofty Aspirations Consultants Ltd.",
    "Logic Tutorial Center - 勵致研習中心",
    "Logos Wealth Management Group Co Ltd - Logos Wealth Management Group Co Ltd",
    "LT Securities Limited - 利通證券有限公司",
    "Lyreco (Hong Kong) Company Limited - Lyreco (Hong Kong) Company Limited",
    "M.S.W. Holdings Ltd - M.S.W. Holdings Ltd",
    "Macquarie - 麥格理銀行",
    "Macroview Telecom Group - Macroview Telecom Group",
    "Mad Head Limited - Mad Head Limited",
    "Madame Tussauds Hong Kong - 香港杜莎夫人蠟像館",
    "Mandarin Oriental Hotel Hong Kong - 香港文華東方酒店",
    "Mannings - 萬寧",
    "Mansyun Association Ltd. - Mansyun Association Ltd.",
    "Manulife - 宏利",
    "Manwor - Manwor",
    "Maples Group  - Maples Group",
    "Massachusetts Mutual Life Insurance Company - 美國萬通",
    "Maxim - 美心集團",
    "Maxway Education Group Limited - Maxway Education Group Limited",
    "Mayer Brown JSM - Mayer Brown JSM",
    "Mazars - Mazars",
    "McKinsey Consulting - McKinsey Consulting",
    "Medical device - Medical device",
    "Medtronic Hong Kong Medical Limited  - Medtronic Hong Kong Medical Limited",
    "Meinhardt (C&S) Limited - Meinhardt (C&S) Limited",
    "Meinhardt (M&E) Limited - 邁進機電工程顧問有限公司",
    "Mentholatum  - 曼秀雷敦",
    "Metrojet - Metrojet",
    "Microsoft Hong Kong - 微軟",
    "Million Base International Limited - Million Base International Limited",
    "Millward Brown TNS - Millward Brown TNS",
    "Mindvivid Limited - Mindvivid Limited",
    "minggarden - 名苑",
    "MinterEllison LLP - 銘德律師事務所",
    "Mirae Asset Global Investment - Mirae Asset Global Investment",
    "Mizuho - 瑞穗银行",
    "Modern Testing Services (Global) Ltd. - 現代技術有限公司",
    "Moore Stephens CPA Limited - 大華馬施雲會計師事務所有限公司",
    "Morden - Morden",
    "Morgan Stanley - 摩根士丹利",
    "Mott MacDonald - Mott MacDonald",
    "MTR Corporation Limited - 香港鐵路有限公司",
    "Mufg Bank, Ltd. - 三菱銀行",
    "MUJI (HK) - 無印良品",
    "Multiable - 萬達寶公司",
    "Muse Group Limited - 木棉",
    "MVA Hong Kong - MVA Hong Kong",
    "Nan Fung Group - 南豐",
    "Nanyang Commercial Bank - 南洋商業銀行",
    "NECHK - 香港日本電氣",
    "Neo Derm - Neo Derm",
    "Nestle Hong Kong Limited - Nestle Hong Kong Limited",
    "Networld Technology Limited - 網匯科技有限公司",
    "New Beta Innovation - 新行健醫藥科技有限公司",
    "New World Construction - 新世界建築有限公司",
    "New World Development - 新世界發展有限公司",
    "Next digital Media - 壹傳媒集團有限公司",
    "Nielsen - 尼爾森",
    "Nixon Cleaning Co., Ltd. - Nixon Cleaning Co., Ltd.",
    "Nomura - 日本野村控股公司",
    "Norton Rose Fulbright - Norton Rose Fulbright",
    "NTK Learning Center Limited - 德勤教育",
    "O P G Human Resources Limited - 東方報業人事資源有限公司",
    "Oasis Medical  - 奧思",
    "OCBC Wing Hang Bank - 華僑永亨銀行",
    "Ocean Park - 香港海洋公園",
    "Octopus Infotech Limited - 八達科技有限公司",
    "Ogilvy and Mather - Ogilvy and Mather",
    "OHL ENGINEERING - OHL ENGINEERING",
    "OK CARE Limited - OK CARE Limited",
    "Okinawa Industry Promotion Public Corporation - Okinawa Industry Promotion Public Corporation",
    "Old age home - Old age home",
    "OmniLearning ECA Centre Limited - OmniLearning ECA Centre Limited",
    "One2Free - One2Free",
    "OneHouse HK Company Ltd. - OneHouse HK Company Ltd.",
    "Online IT magazine - Online IT magazine",
    "OPM System Company Limited - OPM System Company Limited",
    "Oracle - 甲骨文",
    "Orient Overseas Container Line Limited (OOCL) - 東方海外貨櫃航運有限公司 (OOCL)",
    "ORIX ASIA LIMITED - ORIX ASIA LIMITED",
    "Orrick - Orrick",
    "Otic Hearing & Speech Centre - Otic Hearing & Speech Centre",
    "Otto International Hong Kong - Otto International Hong Kong",
    "Oursky Limited - Oursky Limited",
    "Outback - Outback",
    "P&G - 寶潔香港",
    "Parallax Technologies Limited - Parallax Technologies Limited",
    "PARKnSHOP HONG KONG Limited - 百佳超級市場",
    "Parsons Brinckerhoff - Parsons Brinckerhoff",
    "PaulY - 保華",
    "PBA - PBA",
    "PCCW Limited - 電訊盈科企業有限公司",
    "PCCW Solutions - 電訊盈科企業方案",
    "PDL - PDL",
    "PENNY P.C. INVESTMENT COMPANY - PENNY P.C. INVESTMENT COMPANY",
    "PENNY P.C. INVESTMENT COMPANY - PENNY P.C. INVESTMENT COMPANY",
    "Penta-Ocean Construction Co.,Ltd - Penta-Ocean Construction Co.,Ltd",
    "People & Projects Limited - People & Projects Limited",
    "PeopleSearch Ltd - PeopleSearch Ltd",
    "Pernod Ricard - Pernod Ricard",
    "Pfizer - Pfizer",
    "Phillip Securities (HK) Ltd. - 輝立證券(香港)有限公司",
    "Pilot Solution Asia - 柏萊國際亞洲",
    "Po Leung Kuk - 保良局",
    "POPSQUARE LIMITED - POPSQUARE LIMITED",
    "Precious Blood Primary School (South Horizons) - 海怡寶血小學",
    "PricewaterhouseCoopers (PwC) -  羅兵咸永道",
    "Protiviti - 甫瀚",
    "Prudential Hong Kong Limited - 英國保誠",
    "PS - PS",
    "Public Bank (Hong Kong) - 大眾銀行",
    "PVH Asia Limited - PVH Asia Limited",
    "PYPUN-KD - 運基顧問有限公司",
    "Quality HealthCare Medical - 卓健",
    "Quantum (Hong Kong) Limited - Quantum (Hong Kong) Limited",
    "Radica Systems Limited - Radica Systems Limited",
    "Radio Frequency Engineering Ltd. - Radio Frequency Engineering Ltd.",
    "Radio Television Hong Kong - 香港電台",
    "Ramboll  - Ramboll",
    "Rating and Valuation Department - 差餉物業估價署",
    "REC Engineering Company Limited - REC Engineering Company Limited",
    "Regal Motors - Regal Motors",
    "Richemont - Richemont",
    "Ricoh Hong Kong Limited - 理光(香港)",
    "Rider Levett Bucknall Ltd - Rider Levett Bucknall Ltd",
    "Roomservice Limited - Roomservice Limited",
    "RSM Hong Kong - RSM Hong Kong",
    "S & S - S & S",
    "SAE MAGNETICS (HK) LTD - SAE MAGNETICS (HK) LTD",
    "Sage World Group Limited - Sage World Group Limited",
    "Sage World Tuition Centre (Ma On Shan Centre) - Sage World Tuition Centre (Ma On Shan Centre)",
    "San Miguel Brewery HK - San Miguel Brewery HK",
    "Sanfield - 新輝",
    "Sasa - 莎莎",
    "Savills  - Savills",
    "SB Education Center - SB Education Center",
    "Schenker - Schenker",
    "SEB ASIA LTD. - SEB ASIA LTD.",
    "Select Investment Services Limited - Select Investment Services Limited",
    "SF Express - 順豐速運",
    "SFC - 證監會",
    "SGS - 香港通用檢測認證有限公司",
    "Shanghai Commerical Bank - 上海商業銀行",
    "Shangri-La - 香格里拉大酒店",
    "Shearman & Sterling LLP - Shearman & Sterling LLP",
    "Shinewing (HK) CPA Limited - 信永中和香港",
    "Shui On Building Contractors Ltd. - 瑞安建築承包商有限公司",
    "Shui On Construction - Shui On Construction",
    "Shun Hing Systems Integration Co., Ltd - 信興系統工程有限公司",
    "Sidefame Ltd - Sidefame Ltd",
    "Siemens Ltd - Siemens Ltd",
    "Sime Darby Motor Services Limited - Sime Darby Motor Services Limited",
    "Sing Tao News Corporation - 星島報業集團",
    "Sino Estates Management Limited - Sino Estates Management Limited",
    "Sino Land Limited  - 信和置業",
    "Sino Sound Holdings Ltd. - 漢聲集團有限公司",
    "SKH - 聖公會",
    "Slaughter and May - Slaughter and May",
    "Smart Education Co Ltd - Smart Education Co Ltd",
    "Smartone - 數碼通",
    "Snow Hong Kong Development  - 雪花",
    "Socam - Socam",
    "Social Power Limited - Social Power Limited",
    "Societe Generale - 法國興業銀行",
    "Society of Genesis Wise Children Education Centre - Society of Genesis Wise Children Education Centre",
    "South China Morning Post - South China Morning Post",
    "South Ocean Knitters Group - South Ocean Knitters Group",
    "Southa Technical Limited - 南龍機電工程有限公司",
    "SS&C Technologies - SS&C Technologies",
    "Standard & Poor's - Standard & Poor's",
    "Standard Chartered Bank (HK) Limited (SCB) - 渣打銀行(香港)有限公司",
    "Standard International Bank - 國際標準銀行",
    "Stone Arm Company - Stone Arm Company",
    "Strawberrynet - Strawberrynet",
    "Sun Hung Kai Financial - 新鴻基金融集團",
    "Sun Hung Kai Properties - 新鴻基地產",
    "Sun Life Financial Hong Kong - 永明金融",
    "SUPERLUMINAL TECHNOLOGY LIMITED - SUPERLUMINAL TECHNOLOGY LIMITED",
    "Swire - 太古集團",
    "Swire Properties - 太古地產",
    "Swiss Reinsurance Company Ltd - Swiss Reinsurance Company Ltd",
    "Synpulse Hong Kong Limited - Synpulse Hong Kong Limited",
    "TAL Apparel - TAL Apparel",
    "Tang’s living group - Tang’s living group",
    "Teksystems - Teksystems",
    "Television Broadcasts Limited  (TVB) - 電視廣播有限公司",
    "Telstra - Telstra",
    "Tesla Motors - 特斯拉汽車公司",
    "The Boston Consulting Group International GmbH - The Boston Consulting Group International GmbH",
    "The Boys' & Girls' Clubs Association of Hong Kong - The Boys' & Girls' Clubs Association of Hong Kong",
    "The Chinese University of Hong Kong (CUHK) - 香港中文大學",
    "The Continuity Company Limited - The Continuity Company Limited",
    "The Education University of Hong Kong - 香港教育大學",
    "The Executive Centre - 德勤事務所",
    "The Hong Kong and Shanghai Banking Corporation Limited (HSBC) - 香港上海滙豐銀行有限公司",
    "The Hong Kong Federation of Youth Groups - 香港青年協會",
    "The Hong Kong Polytechnic University - The Hong Kong Polytechnic University",
    "The Neighbourhood Advice-Action Council - 鄰舍輔導會",
    "The Open University of Hong Kong - 香港公開大學",
    "The University of Hong Kong - 香港大學",
    "theOrigo Ltd - theOrigo Ltd",
    "Third Bridge Group Limited - Third Bridge Group Limited",
    "Thomson Reuters - Thomson Reuters",
    "Tink Labs Limited - Tink Labs Limited",
    "TNG.Asia Limited - TNG.Asia Limited",
    "Top Express Infrasturture - Top Express Infrasturture",
    "Topone IT Limited - Topone IT Limited",
    "Towngas - 香港中華煤氣有限公司",
    "Tradelink Electronic Commerce Limited - 貿易通",
    "Trane Hong Hong - Trane Hong Hong",
    "Travel Circle International Limited/KUONI - 勝景遊",
    "Travelzoo (Hong Kong) Limited - Travelzoo (Hong Kong) Limited",
    "Tricor Services Limited - Tricor Services Limited",
    "Trip.com - 攜程",
    "Tung Chun - 同珍",
    "Tung Wah Group of Hospitals - 東華三院",
    "TVB - 電視廣播有限公司",
    "TVMost -  毛記電視",
    "Twomonkey - Twomonkey",
    "TXT - TXT",
    "U-Freight Logistics (HK) Ltd. - 聯邦物流(香港)有限公司",
    "UBS - 瑞銀集團",
    "UMH Medical Beauty Group - UMH Medical Beauty Group",
    "UMP Professional Management Limited - UMP Professional Management Limited",
    "Unicorn Stores - Unicorn Stores",
    "Unilever - Unilever",
    "Uniqlo Hong Kong, Limited - Uniqlo Hong Kong, Limited",
    "Unistress Building Construction Limited - 聯力建築有限公司",
    "United Overseas Bank - 大華銀行",
    "Univision Engineering Limited - 聯視",
    "UOB Kay Hian - 大華繼顯",
    "Urban Renewal Authority - 市區重建局",
    "Urbis Limited - 雅邦規劃設計有限公司",
    "Uth Creative Group - 赤子創意",
    "VCC Land Ltd - VCC Land Ltd",
    "VF HK LTD - VF HK LTD",
    "Vibro Construction Company Limited - 惠保建築有限公司",
    "Viral Digital Studio - Viral Digital Studio",
    "Vircon - 雲建",
    "Visual Squares Limited - Visual Squares Limited",
    "Vita Green Health Products Company Limited - 維特健靈",
    "Vita Green Health Products Company Limited - 維特健靈",
    "Vocational Training Council (VTC) - Vocational Training Council (VTC)",
    "W Hong Kong - W Hong Kong",
    "W&L - W&L",
    "Wall Street English  - Wall Street English",
    "Wan Kee Group - 允記集團",
    "Wang On Group Limited - 宏安集團",
    "Wantex Consultants. Co. - Wantex Consultants. Co.",
    "Water Supplies Department - Water Supplies Department",
    "Wavemaker Hong Kong Limited - Wavemaker Hong Kong Limited",
    "Wavemaker Hong Kong Limited - Wavemaker Hong Kong Limited",
    "We Software Limited - We Software Limited",
    "Welab Bank - Welab Bank",
    "Welcome Construction Co. Ltd - 偉金建築",
    "Wellab limited - 匯力(顧問及檢測)",
    "Westco Airconditioning Limited - Westco Airconditioning Limited",
    "Wharf T&T Ltd. - 九倉電訊",
    "WIND INFORMATION (HK) COMPANY LIMITED - WIND INFORMATION (HK) COMPANY LIMITED",
    "Wing On Travel - 永安旅遊",
    "Wise Spread International Limited - Wise Spread International Limited",
    "WorldQuant Investment Consulting (Beijing) Co., Ltd. - WorldQuant Investment Consulting (Beijing) Co., Ltd.",
    "WSP (Asia) Limited - 科進顧問(亞洲)有限公司",
    "WSP Hong Kong Ltd. - 科進香港有限公司",
    "WWP - 文匯報",
    "Wynd Limited - Wynd Limited",
    "Ximco Insurance Brokers Limited - Ximco Insurance Brokers Limited",
    "XY CAPITAL LIMITED - XY CAPITAL LIMITED",
    "Yau Lee Construction Co. Ltd. - Yau Lee Construction Co. Ltd.",
    "YFLife - 萬通保險",
    "YKK Hong Kong Ltd. - YKK香港有限公司",
    "Yoshinoya Hong Kong - 吉野家",
    "YPT International Ltd - 建宏",
    "YU, CHAN & YEUNG SOLICITORS - YU, CHAN & YEUNG SOLICITORS",
    "Zara - Zara",
    "Zarathustra Financial Data Services - Zarathustra Financial Data Services",
    "Zurich Services (Hong Kong) Limited - Zurich Services (Hong Kong) Limited",
    "康倍加 - 康倍加",
    "新輝建築有限公司 - 新輝建築有限公司",
    "東華三院 - 東華三院",
    "珠江船務集團 - 珠江船務集團",
    "美豪 - 美豪"
];
const positions = [
    "Account Executive",
    "Account Manager",
    "Accountant",
    "Accounting Assistant",
    "Actuarial Analyst",
    "Admin",
    "Administration Assistant Manager",
    "Administrative - Finance Assistant",
    "Administrative Assistant",
    "Administrative Officer (AO)",
    "Advisory",
    "Advisory (BPS)",
    "Advisory (IT)",
    "Aircraft Engineering Licence Trainee",
    "Analyst",
    "Analyst (FICC Sales)",
    "Analyst (Fixed Income Sales)",
    "Analyst (IBD)",
    "Analyst (IT)",
    "Analyst (Operation)",
    "Analyst (Sales and Trading)",
    "Analyst Developer (IT)",
    "Analyst Programmer (AP)",
    "Analyst Programmer 2 (AP2)",
    "Analyst Programmer I (AP1)",
    "Analyst Trainee",
    "Application Developer",
    "Arborist",
    "Architect",
    "Architectural Assistant",
    "Asset Management",
    "Assistance Merchandiser",
    "Assistant",
    "Assistant (PTA)",
    "Assistant Branch Manager",
    "Assistant Brand Manager",
    "Assistant Building Service Engineer",
    "Assistant Building Service Inspector",
    "Assistant Chemist",
    "Assistant Clerical Officer",
    "Assistant Creative Designer",
    "Assistant Data Analyst",
    "Assistant Designer",
    "Assistant Editor",
    "Assistant Engineer",
    "Assistant Engineer (Builder)",
    "Assistant Engineer (Building Services)",
    "Assistant Engineer (Civil)",
    "Assistant Engineering Officer",
    "Assistant Environmental Consultant",
    "Assistant Environmental Engineer",
    "Assistant Environmental Officer",
    "Assistant Executive",
    "Assistant Fashion Designer",
    "Assistant Hospital Manager",
    "Assistant Human Resources Manager",
    "Assistant Information Officer",
    "Assistant Interior Designer",
    "Assistant Investigator",
    "Assistant IT Officer",
    "Assistant Labour Officer",
    "Assistant Landscape Designer",
    "Assistant Manager",
    "Assistant Marketing Manager",
    "Assistant Marketing Officer",
    "Assistant Mechanical Engineer",
    "Assistant Operations Manager",
    "Assistant Process Control Engineer",
    "Assistant Producer",
    "Assistant Product Manager",
    "Assistant Professor",
    "Assistant Programme Officer",
    "Assistant Property Officer",
    "Assistant Quality Surveyor",
    "Assistant R&D Manager",
    "Assistant Radiochemist",
    "Assistant Social Work Officer (ASWO)",
    "Assistant System Engineer",
    "Assistant Team Leader",
    "Assistant Technical Officer",
    "Assistant Technician",
    "Assistant Trade Officer",
    "Assistant Transport Officer",
    "Associate",
    "Associate (Advisory)",
    "Associate (Audit)",
    "Associate (Consulting)",
    "Associate (FICC Sales)",
    "Associate (Fixed Income Sales)",
    "Associate (IBD)",
    "Associate (IT)",
    "Associate (Tax)",
    "Associate 1",
    "Associate 1 (Business Risk Services)",
    "Associate Analyst",
    "Associate Consultant",
    "Associate Consultant (Banking Technology)",
    "Associate Consultant, Electromagnetic Compatibility (Automotive & Electronics Division)",
    "Associate Medical Technologist",
    "Audit Trainee",
    "Auditor",
    "AVP",
    "BIM Consultant",
    "BIM Technician I",
    "Brand Executive",
    "Building Engineer",
    "Building Services Engineer",
    "Business Analyst",
    "Business Development Executive",
    "Business Development Trainee",
    "Business Executive",
    "Business Speacialist",
    "Business Support Executive",
    "Business Technology Consultant",
    "Buyer",
    "Captain",
    "Cashier",
    "Catagory Assistant",
    "Category Assistant",
    "Centre Assistant",
    "CEO",
    "Chainman",
    "Channel Manager (Insurance division)",
    "Chemist",
    "Chemist Trainee",
    "Civil Engineer",
    "Civil Engineering Graduate",
    "Clerical Assistant",
    "Clerk",
    "Clerk II",
    "Client Service Associate (PWM)",
    "Commercial Group Graduate Trainee Program",
    "Commercial trainee",
    "Commis 1",
    "Community & Event Assistant",
    "Company Secretarial Associate",
    "Complete Banker Program (IBD)",
    "Compliance",
    "Compliance Anaylst",
    "Compliance Manager",
    "Compliance Specialist",
    "Consultant",
    "Consultant (Banking Technology)",
    "Consultant, Testing and Product Development (Automotive & Electronics Division)",
    "Consulting (Digital)",
    "Consulting Analyst",
    "Content Marketing Intern/ Community Lead",
    "Contract Quality Assurance Analyst",
    "Copywriter",
    "Corporate Administrative trainee",
    "Corporate Management Trainee",
    "Counter Service Officer",
    "Credit Risk Analyst",
    "Customer Care Officer",
    "Customer Due Diligence Officer",
    "Customer Relations Officer",
    "Customer Relationship Officer",
    "Customer Service",
    "Customer Service and Operation Trainee",
    "Customer Service Executive",
    "Customer Service Executive Trainee",
    "Customer Service Manager",
    "Customer Service Officer",
    "Customer Service Representative",
    "Customer Services Engineer",
    "Customer Services Officer",
    "Cybersecurity Analyst",
    "Data Analyst",
    "Data Center Operator",
    "Data Engineer",
    "Data Entry Officer",
    "Data Operation Associate",
    "Dental Hygienist",
    "Dental Surgery Assistant",
    "Design Officer II",
    "Developer",
    "Developer (Android)",
    "Developer (iOS)",
    "Digital Marketing / Content Marketing",
    "Digital Marketing / Performance Marketing",
    "Digital Marketing Executive",
    "Digital Trainee",
    "Director (IBD)",
    "Dispenser",
    "Division Manager",
    "DOJ Legal Trainee",
    "Draftsman (Building Service)",
    "DSA",
    "DTSL internship program (Marketing Assistant)",
    "DTSL internship program (Technical Service Engineer)",
    "Editor",
    "Editor Trainee",
    "Electoral Assistant",
    "Electronic Engineer",
    "Electronic Technician",
    "Engineer",
    "Engineer (Electrical)",
    "Engineer Assistant",
    "Engineer II",
    "Engineer Trainee",
    "Engineering Assistant",
    "Engineering Graduate Trainee",
    "Engineering Trainee",
    "English Language Teaching (ELT)",
    "Enterprise Risk Services",
    "Equity Research (Summer Analyst)",
    "Executive",
    "Executive Assistant",
    "Executive Engineer",
    "Executive Officer (EO)",
    "Executive Trainee",
    "Finance Trainee",
    "Financial Consultant",
    "Financial Data Analyst",
    "Financial Products Analytics & Sales",
    "Financial Service Trainee",
    "Financial services",
    "Financial Trainee",
    "Fitter",
    "Foreman",
    "Founder",
    "Freelance Writer",
    "Front-end Developer",
    "Fund Accounting Officer",
    "GBS consulting by degree",
    "General Banking Manager",
    "General Banking Officer I",
    "Genius",
    "Global Banking Advisory",
    "Global Banking Client Management",
    "Global Banking Markets",
    "Global Data Analyst",
    "Global Future Leader Development Program",
    "Global Graduate (Commercial Banking)",
    "Global Graduate (Securities Service)",
    "Global Graduate Trainee Program",
    "GMI Product Consultant",
    "Graduate Actuarial",
    "Graduate Analyst (Back Office, non-IT)",
    "Graduate Analyst (Corporate Banking)",
    "Graduate Analyst (Equity Research)",
    "Graduate Analyst (Finance)",
    "Graduate Analyst (Global Markets)",
    "Graduate Analyst (IBD)",
    "Graduate Analyst (Operations)",
    "Graduate Analyst (Private Banking)",
    "Graduate Analyst (Private Wealth Management)",
    "Graduate Analyst (Sales & Trading)",
    "Graduate Analyst (Technology)",
    "Graduate Architect",
    "Graduate Associate",
    "Graduate Associate (Technology and Operation)",
    "Graduate Economist",
    "Graduate Engineer",
    "Graduate Engineer (Assistant Building Engineer)",
    "Graduate Engineer (Assistant Building Services Engineer)",
    "Graduate Engineer (Building Engineering)",
    "Graduate Engineer (Building)",
    "Graduate Engineer(AQS)",
    "Graduate Engineer(E&M)",
    "Graduate Engineer(ME)",
    "Graduate Engineer(Scheme A)",
    "Graduate Environmental Consultant",
    "Graduate Environmental Consultant",
    "Graduate Intern",
    "Graduate Program",
    "Graduate Technical Trainee",
    "Graduate Traffic Engineer",
    "Graduate Trainee",
    "Graduate Trainee (Building Services)",
    "Graduate Trainee (Channels)/(Property)/(Marketing)",
    "Graduate Trainee (Chemical)",
    "Graduate Trainee (Civil)",
    "Graduate Trainee (Commercial Banking)",
    "Graduate Trainee (Commercial Group Sales and Marketing)",
    "Graduate Trainee (Corporate)",
    "Graduate Trainee (Electrical)",
    "Graduate Trainee (Electronic)",
    "Graduate Trainee (Energy)",
    "Graduate Trainee (Environmental)",
    "Graduate Trainee (Equity Research)",
    "Graduate Trainee (Geologist)",
    "Graduate Trainee (Geotechnical)",
    "Graduate Trainee (ICT)",
    "Graduate Trainee (IT)",
    "Graduate Trainee (Mechanical)",
    "Graduate Trainee (Ops)",
    "Graduate Trainee (Prime Brokerage)",
    "Graduate Trainee (QS)",
    "Graduate Trainee (Retail Banking)",
    "Graduate Trainee (Retail)",
    "Graduate Trainee (Treasury)",
    "Graduate Trainee (Wealth Management)",
    "Graduate Trainee(HR)",
    "Graduated Master(GM)",
    "Greater China Sales Development Manager",
    "Guest Experience Host",
    "Guest Service Supervisor",
    "Helpdesk",
    "Homework Tutorial Class Teacher",
    "Hong Kong Settlement",
    "House Officer",
    "Housekeeping Supervisor",
    "Human Resources & Administration Assistant",
    "Human Resources & Marketing Officer",
    "Human Resources Assistant",
    "Human Resources Officer",
    "ICT Assoicate",
    "ICT Graduate Trainee",
    "Immigration Assistant",
    "Imterior design assistant",
    "In-house Designer",
    "In-house Photographer",
    "Industrial Placement Trainee",
    "Industrial Placement Trainee (Customer Relation Management)",
    "Interior Designer",
    "Internal Auditor",
    "International Graduate",
    "International Graduate (Corporate Finance, IBD)",
    "International Graduate (Financial Markets, S&T)",
    "International Graduate (Wealth Management)",
    "International Talent Program",
    "International Talent Program (Management Trainee)",
    "Inventory specialist",
    "Investment Banking Development (IBD)",
    "Investment Banking Development trainee (IBD)",
    "IT Analyst",
    "IT Analyst (IT Graduate)",
    "IT and Operations Analyst",
    "IT Associate",
    "IT Consultant",
    "IT Graduate Trainee",
    "IT Graduate Trainee (Assistant Technical Analyst)",
    "IT Officer",
    "IT Specialist",
    "IT Specialist",
    "IT Specialist Trainee",
    "IT Support",
    "IT System Analyst",
    "IT System Engineer",
    "IT Trainee Programme",
    "Java Programmer",
    "Junior Accountant",
    "Junior Accounts Clerk",
    "Junior Analyst",
    "Junior Designer",
    "Junior Marketing Assistant",
    "Junior Programmer",
    "Junior Research Assistant (CSE)",
    "Junior Software Developer",
    "Junior Systems Engineer",
    "Kerry Logistics Internship Programme",
    "KYC",
    "KYC Contract",
    "Laboratory Helper",
    "Laboratory Officer",
    "Land Surveyor",
    "Lecturer",
    "Legal Trainee",
    "Liasion Officer",
    "Maintenance Officer",
    "Makeup Artist",
    "Management Associate",
    "Management Associate (Commercial Banking)",
    "Management Associate (Regional Specialist)",
    "Management Associate (Retail Banking)",
    "Management Consulting (BPS)",
    "Management Director (IBD)",
    "Management Trainee",
    "Management Trainee (Business)",
    "Management Trainee (Corporate Banking)",
    "Management Trainee (Corporate)",
    "Management Trainee (HR)",
    "Management Trainee (Sales & Merchandising)",
    "Management Trainee (Tech and Ops)",
    "Management Trainee (Technical Stream)",
    "Manager",
    "Manager Trainee",
    "Marine Graduate Trainee",
    "Marketing / Account Services",
    "Marketing Assistant",
    "Marketing Associate",
    "Marketing Executive",
    "Marketing Executive",
    "Marketing Graduate Trainee",
    "Marketing Management Trainee",
    "Marketing Manager",
    "Marketing Officer",
    "Marketing Officer (back office)",
    "Marketing Specialist",
    "Marketing Trainee",
    "Mechanical Engineer",
    "Mechanical Engineering Graduate",
    "Media Assistant",
    "Media Executive",
    "Medical Imaging Software Engineer",
    "Medical Officer",
    "Merchandise Planning Manager",
    "Merchandiser",
    "Merchandising Assistant",
    "Mobile App Engineer",
    "Mobile Application Programmer (Android, iOS / iPhone)",
    "Multimedia designer",
    "Network Engineer",
    "Network Operation Centre",
    "News Anchor/ Reporter",
    "Nurse (Registered/Enrolled)",
    "Nurse 護士",
    "Nutritionist",
    "Occupational therapist II 二級職業治療師",
    "Office Administrator",
    "Office Manager",
    "Office Trainee (Corporate Banking)",
    "Office Trainee (Retail Banking)",
    "Officer",
    "Officer Trainee",
    "Operation Assistant",
    "Operation Management Trainee",
    "Operations Manager",
    "Operations Middle / Back Office Trainee",
    "Operator",
    "Optometrist",
    "Outreaching Coordinator",
    "PA",
    "Paralegal",
    "Passenger Service Officer",
    "Patent Engineer",
    "Personal Secretary",
    "Pharmacist",
    "Pharmacist",
    "Physiotherapist",
    "Physiotherapist II 二級物理治療師",
    "Pilot",
    "Planner",
    "PMC",
    "Principle Consultant",
    "Private Banking Analyst",
    "Private Equity Analyst",
    "Probationary Inspector",
    "Process Engineer",
    "Product Development and Resesrch - office",
    "Product Manager",
    "Product Marketing Engineer",
    "Product Packaging Assistant",
    "Product Specialist",
    "Production",
    "Programme Executive (PE)",
    "Programmer",
    "Programmer I",
    "Programmer II",
    "Project Analyst",
    "Project Assistant",
    "Project Associate",
    "Project Coordinator",
    "Project Engineer",
    "Project Executive",
    "Project Manager",
    "Project Officer",
    "Proofreader",
    "Property and Casualty Solutions, Graduate",
    "Property Management Trainee",
    "Property Officer",
    "Psychiatrist",
    "Public Relation Officer (PRO)",
    "Purchasing Assistant",
    "Quality Assurance Analyst (Contract)",
    "Quality Control Technician",
    "Quantitative Analyst",
    "Quantitative Research",
    "Quantitative Research & Development",
    "Quantitative Trader",
    "Quantity Surveyor",
    "Quantity Surveyor",
    "Receptionist",
    "Recruitment Assistant",
    "Regional Head",
    "Registered Nurse",
    "Registered Nurse (Psychiatric)",
    "Relationship Manager",
    "Reporter",
    "Research Analyst",
    "Research Analyst (FinTech)",
    "Research Assistant",
    "Research Associate",
    "Research Editor",
    "Research Executive",
    "Researcher",
    "Resident Pharmacist",
    "Responsible Officer",
    "Risk Advisory Analyst",
    "Risk Advisory Senior Associate",
    "Risk Management Analyst",
    "Risk Officer",
    "Safety Officer",
    "Safety Supervisor",
    "Sales",
    "Sales & Marketing Officer",
    "Sales Administrator",
    "Sales and Analytics",
    "Sales and Marketing Executive",
    "Sales and Merchandising Manager",
    "Sales Associate",
    "Sales Clerk",
    "Sales Clerk",
    "Sales Coordinator",
    "Sales Coordinator",
    "Sales Engineer",
    "Sales Executive",
    "Sales Manager",
    "Sales Representative",
    "Sales Service Assistant",
    "Sales Specialist Trainee",
    "Salesforce Consultant",
    "Salesperson",
    "Scheduling Officer / Manager",
    "Second Officer",
    "Securities Service Analyst (Global Banking and Markets)",
    "Senior Account Executive",
    "Senior Application Developer",
    "Senior Associate, Assurance",
    "Senior Associate, Strategy and Transactions",
    "Senior Auditor",
    "Senior Consultant",
    "Senior Customer Service Officer",
    "Senior Engineer (Algorithm & Software Development)",
    "Senior Engineer (BS)",
    "Senior Financial Analyst",
    "Senior Financial Analyst Officer",
    "Senior Foreman",
    "Senior Foreman",
    "Senior Logistics Administrator",
    "Senior Manager",
    "Senior Marketing Executive",
    "Senior Marketing Manager",
    "Senior Officer",
    "Senior Salesforce Consultant",
    "Senior Software Engineer",
    "Senior Solution Analyst",
    "Senior Solution Consultant",
    "Senior Solution Executive",
    "Senior System Specialist",
    "Senior Teacher",
    "Senior Technical Officer",
    "Senior Translator",
    "Senior Vice President",
    "Service specialist",
    "Service Technician",
    "Ship Master",
    "Social Media Analyst",
    "Social Media Executive",
    "Social Worker",
    "Software Engineer",
    "Software Engineer",
    "Software Engineer Trainee",
    "Solution Developer",
    "Solutions Group Asia, Graduate",
    "Specialist",
    "Staff Accountant",
    "Station Officer",
    "Store leader",
    "Store Management Trainee",
    "Store Manager",
    "Strategy Analyst",
    "Strategy Intern",
    "Structural Enginnering Graduate",
    "Student helper",
    "Summer Analyst (Global Markets)",
    "Summer Analyst (IBD)",
    "Summer Intern",
    "Summer Trainee",
    "Supervisor Trainee",
    "Support Consultant",
    "Survey Officer",
    "Surveyor Trainee",
    "System Administration",
    "System Analyst",
    "System Analyst 1",
    "System Analyst Trainee",
    "System Associate",
    "System Engineer",
    "System Support",
    "Tax Associate 1",
    "Teacher",
    "Teacher Assistant",
    "Teacher of Biology",
    "Teacher of Chinese",
    "Teacher of Economics",
    "Teacher of Mathematics",
    "Teaching Assistant",
    "Teaching Associate",
    "Technical Analyst",
    "Technical Consultant",
    "Technical Director",
    "Technical Engineer",
    "Technical Officer",
    "Technical Service Engineer",
    "Technical Specialist",
    "Technical Support Engineer",
    "Technical Trainee",
    "Technician",
    "Technician Associate",
    "Technology Analyst",
    "Technology and Operations Management Trainee",
    "Telesales Agent",
    "Teller",
    "Testing Software Engineer",
    "Trader",
    "Trainee",
    "Trainee (Commercial Support)",
    "Trainee (COO Assistant)",
    "Trainee (Cross Asset Derivatives Marketer)",
    "Trainee (Developer, Finance, Risk, Market Data)",
    "Trainee (E-Client Services)",
    "Trainee (Front Office Application Developer)",
    "Trainee (Internal Audit)",
    "Trainee (Market Access Quality Assurance)",
    "Trainee (Market Activity Analyst)",
    "Trainee (One Delta Index Trading)",
    "Trainee (Project Management Officer)",
    "Trainee (Trade Commodity Finance)",
    "Trainee (Trading Support Unit)",
    "Trainee (underwriting /claims)",
    "Trainee Solicitor",
    "Trainee Teacher",
    "Training Officer",
    "Translator",
    "Transport Officer II",
    "Tutor",
    "UI / UX 2D 3D Graphics Designer",
    "Unity Developer",
    "User Interaction Designer (UI/UX)",
    "UX Designer",
    "Valuation Officer Trainee",
    "Veterinary Assistant",
    "Vice President",
    "Vice President (Back Office)",
    "Vice President (FICC Sales)",
    "Vice President (Fixed Income Sales)",
    "Vice President (IBD)",
    "Vice President (IT)",
    "Video Producer",
    "Visual Merchandiser",
    "Visual merchandiser",
    "Waiter",
    "Warehouse Staff",
    "Wealth Management Manager",
    "Web Developer",
    "Web Programmer",
    "Welfare Worker",
    "Winter Intern",
    "Works Supervisor II",
    "WS2",
    "一級技術員",
    "中文科教師",
    "二級技術員",
    "停機坪行李處理員",
    "兒童繪畫班導師",
    "入境主任",
    "兼職兒童花式跳繩課程導師",
    "到校功課班導師",
    "功課輔導班導師",
    "助理管工",
    "字幕員",
    "學徒",
    "工人",
    "工程助理",
    "工程師",
    "幼兒工作員",
    "廚師",
    "懲教主任",
    "房屋事務主任",
    "技術員",
    "教學助理",
    "會計文員",
    "服務幹事",
    "樓面",
    "消防隊目(控制)",
    "秘書",
    "美容師",
    "老師",
    "興趣班導師",
    "註冊中醫師",
    "電工",
    "韓文導師"
];

export function getCompanies() {
    return companies;
}
export function getIndusties() {
    return industries;
}
export function getPositions() {
    return positions;
}